/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Stub implementations for amdhip64_7.dll exports that the
 * hip-remote-client does not implement. These stubs return
 * hipErrorNotSupported (801) so that callers get a clear error
 * rather than a missing-symbol crash.
 *
 * Generated by gen_def.py
 */

typedef int hipError_t;

/* ============================================================================
 * Variable exports
 * ============================================================================ */

int AMD_CPU_AFFINITY = 0;
int AMD_DIRECT_DISPATCH = 0;
int AMD_GPU_FORCE_SINGLE_FP_DENORM = 0;
int AMD_LOG_LEVEL = 0;
int AMD_LOG_LEVEL_FILE = 0;
int AMD_LOG_LEVEL_SIZE = 0;
int AMD_LOG_MASK = 0;
int AMD_OCL_BUILD_OPTIONS = 0;
int AMD_OCL_BUILD_OPTIONS_APPEND = 0;
int AMD_OCL_LINK_OPTIONS = 0;
int AMD_OCL_LINK_OPTIONS_APPEND = 0;
int AMD_OCL_WAIT_COMMAND = 0;
int AMD_OPT_FLUSH = 0;
int AMD_SERIALIZE_COPY = 0;
int AMD_SERIALIZE_KERNEL = 0;
int AMD_THREAD_TRACE_ENABLE = 0;
int CL_KHR_FP64 = 0;
int CQ_THREAD_STACK_SIZE = 0;
int CUDA_VISIBLE_DEVICES = 0;
int DEBUG_CLR_BATCH_CPU_SYNC_SIZE = 0;
int DEBUG_CLR_BLIT_KERNARG_OPT = 0;
int DEBUG_CLR_KERNARG_HDP_FLUSH_WA = 0;
int DEBUG_CLR_LIMIT_BLIT_WG = 0;
int DEBUG_CLR_MAX_BATCH_SIZE = 0;
int DEBUG_CLR_SYSMEM_POOL = 0;
int DEBUG_HIP_BLOCK_SYNC = 0;
int DEBUG_HIP_DYNAMIC_QUEUES = 0;
int DEBUG_HIP_FORCE_ASYNC_QUEUE = 0;
int DEBUG_HIP_FORCE_GRAPH_QUEUES = 0;
int DEBUG_HIP_GRAPH_BATCH_SIZE = 0;
int DEBUG_HIP_GRAPH_DOT_PRINT = 0;
int DEBUG_HIP_GRAPH_SEGMENT_SCHEDULING = 0;
int DEBUG_HIP_IGNORE_STREAM_PRIORITY = 0;
int DEBUG_HIP_KERNARG_COPY_OPT = 0;
int DEBUG_HIP_MEM_POOL_VMHEAP = 0;
int DISABLE_DEFERRED_ALLOC = 0;
int GPU_ADD_HBCC_SIZE = 0;
int GPU_ANALYZE_HANG = 0;
int GPU_BLIT_ENGINE_TYPE = 0;
int GPU_CP_DMA_COPY_SIZE = 0;
int GPU_DEBUG_ENABLE = 0;
int GPU_DEVICE_ORDINAL = 0;
int GPU_DUMP_BLIT_KERNELS = 0;
int GPU_DUMP_CODE_OBJECT = 0;
int GPU_ENABLE_COOP_GROUPS = 0;
int GPU_ENABLE_HW_P2P = 0;
int GPU_ENABLE_PAL = 0;
int GPU_ENABLE_WAVE32_MODE = 0;
int GPU_ENABLE_WGP_MODE = 0;
int GPU_FLUSH_ON_EXECUTION = 0;
int GPU_FORCE_BLIT_COPY_SIZE = 0;
int GPU_FORCE_QUEUE_PROFILING = 0;
int GPU_IMAGE_BUFFER_WAR = 0;
int GPU_IMAGE_DMA = 0;
int GPU_MAX_COMMAND_BUFFERS = 0;
int GPU_MAX_HEAP_SIZE = 0;
int GPU_MAX_HW_QUEUES = 0;
int GPU_MAX_REMOTE_MEM_SIZE = 0;
int GPU_MAX_RESOURCE_CACHE_SIZE = 0;
int GPU_MAX_SUBALLOC_SIZE = 0;
int GPU_MAX_USWC_ALLOC_SIZE = 0;
int GPU_MAX_WORKGROUP_SIZE = 0;
int GPU_MIPMAP = 0;
int GPU_NUM_COMPUTE_RINGS = 0;
int GPU_NUM_MEM_DEPENDENCY = 0;
int GPU_PINNED_MIN_XFER_SIZE = 0;
int GPU_PINNED_XFER_SIZE = 0;
int GPU_PRINT_CHILD_KERNEL = 0;
int GPU_RESOURCE_CACHE_SIZE = 0;
int GPU_SINGLE_ALLOC_PERCENT = 0;
int GPU_STAGING_BUFFER_SIZE = 0;
int GPU_STREAMOPS_CP_WAIT = 0;
int GPU_USE_DEVICE_QUEUE = 0;
int GPU_WAVES_PER_SIMD = 0;
int GPU_XFER_BUFFER_SIZE = 0;
int HIPRTC_COMPILE_OPTIONS_APPEND = 0;
int HIPRTC_LINK_OPTIONS_APPEND = 0;
int HIPRTC_USE_RUNTIME_UNBUNDLER = 0;
int HIP_FORCE_DEV_KERNARG = 0;
int HIP_FORCE_SPIRV_CODEOBJECT = 0;
int HIP_HIDDEN_FREE_MEM = 0;
int HIP_HOST_COHERENT = 0;
int HIP_INITIAL_DM_SIZE = 0;
int HIP_LAUNCH_BLOCKING = 0;
int HIP_MEM_POOL_SUPPORT = 0;
int HIP_MEM_POOL_USE_VM = 0;
int HIP_SKIP_ABORT_ON_GPU_ERROR = 0;
int HIP_VISIBLE_DEVICES = 0;
int HIP_VMEM_MANAGE_SUPPORT = 0;
int HSA_KERNARG_POOL_SIZE = 0;
int HSA_LOCAL_MEMORY_ENABLE = 0;
int OCL_SET_SVM_SIZE = 0;
int OCL_STUB_PROGRAMS = 0;
int OPENCL_VERSION = 0;
int PAL_ALWAYS_RESIDENT = 0;
int PAL_DISABLE_SDMA = 0;
int PAL_EMBED_KERNEL_MD = 0;
int PAL_FORCE_ASIC_REVISION = 0;
int PAL_HIP_IPC_FLAG = 0;
int PAL_MALL_POLICY = 0;
int PAL_PREPINNED_MEMORY_SIZE = 0;
int PAL_RGP_DISP_COUNT = 0;
int REMOTE_ALLOC = 0;
int ROC_ACTIVE_WAIT_TIMEOUT = 0;
int ROC_AQL_QUEUE_SIZE = 0;
int ROC_CPU_WAIT_FOR_SIGNAL = 0;
int ROC_ENABLE_LARGE_BAR = 0;
int ROC_GLOBAL_CU_MASK = 0;
int ROC_HMM_FLAGS = 0;
int ROC_P2P_SDMA_SIZE = 0;
int ROC_SIGNAL_POOL_SIZE = 0;
int ROC_SKIP_KERNEL_ARG_COPY = 0;
int ROC_SYSTEM_SCOPE_SIGNAL = 0;
int ROC_USE_FGS_KERNARG = 0;

/* ============================================================================
 * C++ mangled export stubs
 *
 * These are C++ overloads from the real DLL. We provide C-linkage stubs
 * that the .def file maps to the mangled export names.
 * ============================================================================ */

hipError_t __stub_mangled_1(void) { return 801; }
hipError_t __stub_mangled_2(void) { return 801; }

/* ============================================================================
 * Function stubs (hipErrorNotSupported = 801)
 * ============================================================================ */

hipError_t __gnu_f2h_ieee(void) { return 801; }
hipError_t __gnu_h2f_ieee(void) { return 801; }
hipError_t __hipRegisterManagedVar(void) { return 801; }
hipError_t __hipRegisterSurface(void) { return 801; }
hipError_t __hipRegisterTexture(void) { return 801; }
hipError_t amd_dbgapi_get_build_id(void) { return 801; }
hipError_t amd_dbgapi_get_build_name(void) { return 801; }
hipError_t amd_dbgapi_get_git_hash(void) { return 801; }
hipError_t hipApiName(void) { return 801; }
hipError_t hipArray3DCreate(void) { return 801; }
hipError_t hipArray3DGetDescriptor(void) { return 801; }
hipError_t hipArrayCreate(void) { return 801; }
hipError_t hipArrayDestroy(void) { return 801; }
hipError_t hipArrayGetDescriptor(void) { return 801; }
hipError_t hipArrayGetInfo(void) { return 801; }
hipError_t hipBindTexture(void) { return 801; }
hipError_t hipBindTexture2D(void) { return 801; }
hipError_t hipBindTextureToArray(void) { return 801; }
hipError_t hipBindTextureToMipmappedArray(void) { return 801; }
hipError_t hipChooseDeviceR0000(void) { return 801; }
hipError_t hipChooseDeviceR0600(void) { return 801; }
hipError_t hipConfigureCall(void) { return 801; }
hipError_t hipCreateChannelDesc(void) { return 801; }
hipError_t hipCreateSurfaceObject(void) { return 801; }
hipError_t hipCreateTextureObject(void) { return 801; }
hipError_t hipDestroyExternalMemory(void) { return 801; }
hipError_t hipDestroyExternalSemaphore(void) { return 801; }
hipError_t hipDestroySurfaceObject(void) { return 801; }
hipError_t hipDestroyTextureObject(void) { return 801; }
hipError_t hipDeviceComputeCapability(void) { return 801; }
hipError_t hipDeviceGetByPCIBusId(void) { return 801; }
hipError_t hipDeviceGetCacheConfig(void) { return 801; }
hipError_t hipDeviceGetGraphMemAttribute(void) { return 801; }
hipError_t hipDeviceGetMemPool(void) { return 801; }
hipError_t hipDeviceGetName(void) { return 801; }
hipError_t hipDeviceGetP2PAttribute(void) { return 801; }
hipError_t hipDeviceGetPCIBusId(void) { return 801; }
hipError_t hipDeviceGetSharedMemConfig(void) { return 801; }
hipError_t hipDeviceGetTexture1DLinearMaxWidth(void) { return 801; }
hipError_t hipDeviceGetUuid(void) { return 801; }
hipError_t hipDeviceGraphMemTrim(void) { return 801; }
hipError_t hipDeviceSetCacheConfig(void) { return 801; }
hipError_t hipDeviceSetGraphMemAttribute(void) { return 801; }
hipError_t hipDeviceSetMemPool(void) { return 801; }
hipError_t hipDeviceSetSharedMemConfig(void) { return 801; }
hipError_t hipDrvGetErrorName(void) { return 801; }
hipError_t hipDrvGraphAddMemFreeNode(void) { return 801; }
hipError_t hipDrvGraphAddMemcpyNode(void) { return 801; }
hipError_t hipDrvGraphAddMemsetNode(void) { return 801; }
hipError_t hipDrvGraphExecMemcpyNodeSetParams(void) { return 801; }
hipError_t hipDrvGraphExecMemsetNodeSetParams(void) { return 801; }
hipError_t hipDrvGraphMemcpyNodeGetParams(void) { return 801; }
hipError_t hipDrvGraphMemcpyNodeSetParams(void) { return 801; }
hipError_t hipDrvLaunchKernelEx(void) { return 801; }
hipError_t hipDrvMemcpy2DUnaligned(void) { return 801; }
hipError_t hipDrvMemcpy3D(void) { return 801; }
hipError_t hipDrvMemcpy3DAsync(void) { return 801; }
hipError_t hipDrvPointerGetAttributes(void) { return 801; }
hipError_t hipEventRecordWithFlags(void) { return 801; }
hipError_t hipEventRecord_spt(void) { return 801; }
hipError_t hipExtDisableLogging(void) { return 801; }
hipError_t hipExtEnableLogging(void) { return 801; }
hipError_t hipExtGetLinkTypeAndHopCount(void) { return 801; }
hipError_t hipExtLaunchKernel(void) { return 801; }
hipError_t hipExtLaunchMultiKernelMultiDevice(void) { return 801; }
hipError_t hipExtMallocWithFlags(void) { return 801; }
hipError_t hipExtSetLoggingParams(void) { return 801; }
hipError_t hipExternalMemoryGetMappedBuffer(void) { return 801; }
hipError_t hipExternalMemoryGetMappedMipmappedArray(void) { return 801; }
hipError_t hipFreeArray(void) { return 801; }
hipError_t hipFreeMipmappedArray(void) { return 801; }
hipError_t hipFuncSetSharedMemConfig(void) { return 801; }
hipError_t hipGLGetDevices(void) { return 801; }
hipError_t hipGetChannelDesc(void) { return 801; }
hipError_t hipGetCmdName(void) { return 801; }
hipError_t hipGetDeviceFlags(void) { return 801; }
hipError_t hipGetDevicePropertiesR0000(void) { return 801; }
hipError_t hipGetDriverEntryPoint(void) { return 801; }
hipError_t hipGetDriverEntryPoint_spt(void) { return 801; }
hipError_t hipGetFuncBySymbol(void) { return 801; }
hipError_t hipGetMipmappedArrayLevel(void) { return 801; }
hipError_t hipGetProcAddress(void) { return 801; }
hipError_t hipGetProcAddress_spt(void) { return 801; }
hipError_t hipGetSymbolSize(void) { return 801; }
hipError_t hipGetTextureAlignmentOffset(void) { return 801; }
hipError_t hipGetTextureObjectResourceDesc(void) { return 801; }
hipError_t hipGetTextureObjectResourceViewDesc(void) { return 801; }
hipError_t hipGetTextureObjectTextureDesc(void) { return 801; }
hipError_t hipGetTextureReference(void) { return 801; }
hipError_t hipGraphAddBatchMemOpNode(void) { return 801; }
hipError_t hipGraphAddChildGraphNode(void) { return 801; }
hipError_t hipGraphAddExternalSemaphoresSignalNode(void) { return 801; }
hipError_t hipGraphAddExternalSemaphoresWaitNode(void) { return 801; }
hipError_t hipGraphAddHostNode(void) { return 801; }
hipError_t hipGraphAddMemAllocNode(void) { return 801; }
hipError_t hipGraphAddMemFreeNode(void) { return 801; }
hipError_t hipGraphAddMemcpyNodeFromSymbol(void) { return 801; }
hipError_t hipGraphAddMemcpyNodeToSymbol(void) { return 801; }
hipError_t hipGraphAddNode(void) { return 801; }
hipError_t hipGraphBatchMemOpNodeGetParams(void) { return 801; }
hipError_t hipGraphBatchMemOpNodeSetParams(void) { return 801; }
hipError_t hipGraphChildGraphNodeGetGraph(void) { return 801; }
hipError_t hipGraphEventRecordNodeGetEvent(void) { return 801; }
hipError_t hipGraphEventRecordNodeSetEvent(void) { return 801; }
hipError_t hipGraphEventWaitNodeGetEvent(void) { return 801; }
hipError_t hipGraphEventWaitNodeSetEvent(void) { return 801; }
hipError_t hipGraphExecBatchMemOpNodeSetParams(void) { return 801; }
hipError_t hipGraphExecChildGraphNodeSetParams(void) { return 801; }
hipError_t hipGraphExecEventRecordNodeSetEvent(void) { return 801; }
hipError_t hipGraphExecEventWaitNodeSetEvent(void) { return 801; }
hipError_t hipGraphExecExternalSemaphoresSignalNodeSetParams(void) { return 801; }
hipError_t hipGraphExecExternalSemaphoresWaitNodeSetParams(void) { return 801; }
hipError_t hipGraphExecGetFlags(void) { return 801; }
hipError_t hipGraphExecHostNodeSetParams(void) { return 801; }
hipError_t hipGraphExecMemcpyNodeSetParams(void) { return 801; }
hipError_t hipGraphExecMemcpyNodeSetParams1D(void) { return 801; }
hipError_t hipGraphExecMemcpyNodeSetParamsFromSymbol(void) { return 801; }
hipError_t hipGraphExecMemcpyNodeSetParamsToSymbol(void) { return 801; }
hipError_t hipGraphExecMemsetNodeSetParams(void) { return 801; }
hipError_t hipGraphExecNodeSetParams(void) { return 801; }
hipError_t hipGraphExternalSemaphoresSignalNodeGetParams(void) { return 801; }
hipError_t hipGraphExternalSemaphoresSignalNodeSetParams(void) { return 801; }
hipError_t hipGraphExternalSemaphoresWaitNodeGetParams(void) { return 801; }
hipError_t hipGraphExternalSemaphoresWaitNodeSetParams(void) { return 801; }
hipError_t hipGraphHostNodeGetParams(void) { return 801; }
hipError_t hipGraphHostNodeSetParams(void) { return 801; }
hipError_t hipGraphInstantiateWithParams(void) { return 801; }
hipError_t hipGraphKernelNodeCopyAttributes(void) { return 801; }
hipError_t hipGraphKernelNodeGetAttribute(void) { return 801; }
hipError_t hipGraphKernelNodeGetParams(void) { return 801; }
hipError_t hipGraphKernelNodeSetAttribute(void) { return 801; }
hipError_t hipGraphKernelNodeSetParams(void) { return 801; }
hipError_t hipGraphLaunch_spt(void) { return 801; }
hipError_t hipGraphMemAllocNodeGetParams(void) { return 801; }
hipError_t hipGraphMemFreeNodeGetParams(void) { return 801; }
hipError_t hipGraphMemcpyNodeGetParams(void) { return 801; }
hipError_t hipGraphMemcpyNodeSetParams(void) { return 801; }
hipError_t hipGraphMemcpyNodeSetParams1D(void) { return 801; }
hipError_t hipGraphMemcpyNodeSetParamsFromSymbol(void) { return 801; }
hipError_t hipGraphMemcpyNodeSetParamsToSymbol(void) { return 801; }
hipError_t hipGraphMemsetNodeGetParams(void) { return 801; }
hipError_t hipGraphMemsetNodeSetParams(void) { return 801; }
hipError_t hipGraphNodeFindInClone(void) { return 801; }
hipError_t hipGraphNodeGetEnabled(void) { return 801; }
hipError_t hipGraphNodeSetEnabled(void) { return 801; }
hipError_t hipGraphNodeSetParams(void) { return 801; }
hipError_t hipGraphReleaseUserObject(void) { return 801; }
hipError_t hipGraphRemoveDependencies(void) { return 801; }
hipError_t hipGraphRetainUserObject(void) { return 801; }
hipError_t hipGraphUpload(void) { return 801; }
hipError_t hipGraphicsGLRegisterBuffer(void) { return 801; }
hipError_t hipGraphicsGLRegisterImage(void) { return 801; }
hipError_t hipGraphicsMapResources(void) { return 801; }
hipError_t hipGraphicsResourceGetMappedPointer(void) { return 801; }
hipError_t hipGraphicsSubResourceGetMappedArray(void) { return 801; }
hipError_t hipGraphicsUnmapResources(void) { return 801; }
hipError_t hipGraphicsUnregisterResource(void) { return 801; }
hipError_t hipHccModuleLaunchKernel(void) { return 801; }
hipError_t hipHostAlloc(void) { return 801; }
hipError_t hipHostGetDevicePointer(void) { return 801; }
hipError_t hipHostGetFlags(void) { return 801; }
hipError_t hipImportExternalMemory(void) { return 801; }
hipError_t hipImportExternalSemaphore(void) { return 801; }
hipError_t hipKernelGetLibrary(void) { return 801; }
hipError_t hipKernelGetName(void) { return 801; }
hipError_t hipKernelGetParamInfo(void) { return 801; }
hipError_t hipKernelNameRef(void) { return 801; }
hipError_t hipLaunchByPtr(void) { return 801; }
hipError_t hipLaunchCooperativeKernelMultiDevice(void) { return 801; }
hipError_t hipLaunchCooperativeKernel_spt(void) { return 801; }
hipError_t hipLaunchHostFunc_spt(void) { return 801; }
hipError_t hipLaunchKernelExC(void) { return 801; }
hipError_t hipLaunchKernel_spt(void) { return 801; }
hipError_t hipLibraryEnumerateKernels(void) { return 801; }
hipError_t hipLibraryGetKernel(void) { return 801; }
hipError_t hipLibraryGetKernelCount(void) { return 801; }
hipError_t hipLibraryLoadData(void) { return 801; }
hipError_t hipLibraryLoadFromFile(void) { return 801; }
hipError_t hipLibraryUnload(void) { return 801; }
hipError_t hipLinkAddData(void) { return 801; }
hipError_t hipLinkAddFile(void) { return 801; }
hipError_t hipLinkComplete(void) { return 801; }
hipError_t hipLinkCreate(void) { return 801; }
hipError_t hipLinkDestroy(void) { return 801; }
hipError_t hipMalloc3D(void) { return 801; }
hipError_t hipMalloc3DArray(void) { return 801; }
hipError_t hipMallocArray(void) { return 801; }
hipError_t hipMallocFromPoolAsync(void) { return 801; }
hipError_t hipMallocMipmappedArray(void) { return 801; }
hipError_t hipMallocPitch(void) { return 801; }
hipError_t hipMemAddressFree(void) { return 801; }
hipError_t hipMemAddressReserve(void) { return 801; }
hipError_t hipMemAdvise_v2(void) { return 801; }
hipError_t hipMemAllocHost(void) { return 801; }
hipError_t hipMemAllocPitch(void) { return 801; }
hipError_t hipMemCreate(void) { return 801; }
hipError_t hipMemExportToShareableHandle(void) { return 801; }
hipError_t hipMemGetAccess(void) { return 801; }
hipError_t hipMemGetAddressRange(void) { return 801; }
hipError_t hipMemGetAllocationGranularity(void) { return 801; }
hipError_t hipMemGetAllocationPropertiesFromHandle(void) { return 801; }
hipError_t hipMemGetMemPool(void) { return 801; }
hipError_t hipMemImportFromShareableHandle(void) { return 801; }
hipError_t hipMemMap(void) { return 801; }
hipError_t hipMemMapArrayAsync(void) { return 801; }
hipError_t hipMemPoolCreate(void) { return 801; }
hipError_t hipMemPoolDestroy(void) { return 801; }
hipError_t hipMemPoolExportPointer(void) { return 801; }
hipError_t hipMemPoolExportToShareableHandle(void) { return 801; }
hipError_t hipMemPoolGetAccess(void) { return 801; }
hipError_t hipMemPoolImportFromShareableHandle(void) { return 801; }
hipError_t hipMemPoolImportPointer(void) { return 801; }
hipError_t hipMemPrefetchAsync(void) { return 801; }
hipError_t hipMemPrefetchAsync_v2(void) { return 801; }
hipError_t hipMemRangeGetAttribute(void) { return 801; }
hipError_t hipMemRangeGetAttributes(void) { return 801; }
hipError_t hipMemRelease(void) { return 801; }
hipError_t hipMemRetainAllocationHandle(void) { return 801; }
hipError_t hipMemSetAccess(void) { return 801; }
hipError_t hipMemSetMemPool(void) { return 801; }
hipError_t hipMemUnmap(void) { return 801; }
hipError_t hipMemcpy2DArrayToArray(void) { return 801; }
hipError_t hipMemcpy2DAsync_spt(void) { return 801; }
hipError_t hipMemcpy2DFromArray(void) { return 801; }
hipError_t hipMemcpy2DFromArrayAsync(void) { return 801; }
hipError_t hipMemcpy2DFromArrayAsync_spt(void) { return 801; }
hipError_t hipMemcpy2DFromArray_spt(void) { return 801; }
hipError_t hipMemcpy2DToArray(void) { return 801; }
hipError_t hipMemcpy2DToArrayAsync(void) { return 801; }
hipError_t hipMemcpy2DToArrayAsync_spt(void) { return 801; }
hipError_t hipMemcpy2DToArray_spt(void) { return 801; }
hipError_t hipMemcpy2D_spt(void) { return 801; }
hipError_t hipMemcpy3DAsync_spt(void) { return 801; }
hipError_t hipMemcpy3DBatchAsync(void) { return 801; }
hipError_t hipMemcpy3DPeer(void) { return 801; }
hipError_t hipMemcpy3DPeerAsync(void) { return 801; }
hipError_t hipMemcpy3D_spt(void) { return 801; }
hipError_t hipMemcpyAsync_spt(void) { return 801; }
hipError_t hipMemcpyAtoA(void) { return 801; }
hipError_t hipMemcpyAtoD(void) { return 801; }
hipError_t hipMemcpyAtoH(void) { return 801; }
hipError_t hipMemcpyAtoHAsync(void) { return 801; }
hipError_t hipMemcpyBatchAsync(void) { return 801; }
hipError_t hipMemcpyDtoA(void) { return 801; }
hipError_t hipMemcpyDtoDAsync(void) { return 801; }
hipError_t hipMemcpyDtoHAsync(void) { return 801; }
hipError_t hipMemcpyFromArray(void) { return 801; }
hipError_t hipMemcpyFromArray_spt(void) { return 801; }
hipError_t hipMemcpyFromSymbolAsync(void) { return 801; }
hipError_t hipMemcpyFromSymbolAsync_spt(void) { return 801; }
hipError_t hipMemcpyFromSymbol_spt(void) { return 801; }
hipError_t hipMemcpyHtoA(void) { return 801; }
hipError_t hipMemcpyHtoAAsync(void) { return 801; }
hipError_t hipMemcpyHtoDAsync(void) { return 801; }
hipError_t hipMemcpyParam2D(void) { return 801; }
hipError_t hipMemcpyParam2DAsync(void) { return 801; }
hipError_t hipMemcpyToArray(void) { return 801; }
hipError_t hipMemcpyToSymbolAsync(void) { return 801; }
hipError_t hipMemcpyToSymbolAsync_spt(void) { return 801; }
hipError_t hipMemcpyToSymbol_spt(void) { return 801; }
hipError_t hipMemcpy_spt(void) { return 801; }
hipError_t hipMemset2D(void) { return 801; }
hipError_t hipMemset2DAsync(void) { return 801; }
hipError_t hipMemset2DAsync_spt(void) { return 801; }
hipError_t hipMemset2D_spt(void) { return 801; }
hipError_t hipMemset3D(void) { return 801; }
hipError_t hipMemset3DAsync(void) { return 801; }
hipError_t hipMemset3DAsync_spt(void) { return 801; }
hipError_t hipMemset3D_spt(void) { return 801; }
hipError_t hipMemsetAsync_spt(void) { return 801; }
hipError_t hipMemsetD16(void) { return 801; }
hipError_t hipMemsetD16Async(void) { return 801; }
hipError_t hipMemsetD2D16(void) { return 801; }
hipError_t hipMemsetD2D16Async(void) { return 801; }
hipError_t hipMemsetD2D32(void) { return 801; }
hipError_t hipMemsetD2D32Async(void) { return 801; }
hipError_t hipMemsetD2D8(void) { return 801; }
hipError_t hipMemsetD2D8Async(void) { return 801; }
hipError_t hipMemsetD32(void) { return 801; }
hipError_t hipMemsetD32Async(void) { return 801; }
hipError_t hipMemsetD8(void) { return 801; }
hipError_t hipMemsetD8Async(void) { return 801; }
hipError_t hipMemset_spt(void) { return 801; }
hipError_t hipMipmappedArrayCreate(void) { return 801; }
hipError_t hipMipmappedArrayDestroy(void) { return 801; }
hipError_t hipMipmappedArrayGetLevel(void) { return 801; }
hipError_t hipMipmappedArrayGetMemoryRequirements(void) { return 801; }
hipError_t hipModuleGetFunctionCount(void) { return 801; }
hipError_t hipModuleGetGlobal(void) { return 801; }
hipError_t hipModuleGetTexRef(void) { return 801; }
hipError_t hipModuleLaunchCooperativeKernelMultiDevice(void) { return 801; }
hipError_t hipModuleLoadFatBinary(void) { return 801; }
hipError_t hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(void) { return 801; }
hipError_t hipModuleOccupancyMaxPotentialBlockSize(void) { return 801; }
hipError_t hipModuleOccupancyMaxPotentialBlockSizeWithFlags(void) { return 801; }
hipError_t hipOccupancyAvailableDynamicSMemPerBlock(void) { return 801; }
hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(void) { return 801; }
hipError_t hipProfilerStart(void) { return 801; }
hipError_t hipProfilerStop(void) { return 801; }
hipError_t hipRegisterTracerCallback(void) { return 801; }
hipError_t hipSetDeviceFlags(void) { return 801; }
hipError_t hipSetupArgument(void) { return 801; }
hipError_t hipSignalExternalSemaphoresAsync(void) { return 801; }
hipError_t hipStreamAddCallback_spt(void) { return 801; }
hipError_t hipStreamAttachMemAsync(void) { return 801; }
hipError_t hipStreamBatchMemOp(void) { return 801; }
hipError_t hipStreamBeginCaptureToGraph(void) { return 801; }
hipError_t hipStreamBeginCapture_spt(void) { return 801; }
hipError_t hipStreamCopyAttributes(void) { return 801; }
hipError_t hipStreamEndCapture_spt(void) { return 801; }
hipError_t hipStreamGetAttribute(void) { return 801; }
hipError_t hipStreamGetCaptureInfo_spt(void) { return 801; }
hipError_t hipStreamGetCaptureInfo_v2_spt(void) { return 801; }
hipError_t hipStreamGetFlags_spt(void) { return 801; }
hipError_t hipStreamGetId(void) { return 801; }
hipError_t hipStreamGetPriority_spt(void) { return 801; }
hipError_t hipStreamIsCapturing_spt(void) { return 801; }
hipError_t hipStreamQuery_spt(void) { return 801; }
hipError_t hipStreamSetAttribute(void) { return 801; }
hipError_t hipStreamSynchronize_spt(void) { return 801; }
hipError_t hipStreamUpdateCaptureDependencies(void) { return 801; }
hipError_t hipStreamWaitEvent_spt(void) { return 801; }
hipError_t hipStreamWaitValue32(void) { return 801; }
hipError_t hipStreamWaitValue64(void) { return 801; }
hipError_t hipStreamWriteValue32(void) { return 801; }
hipError_t hipStreamWriteValue64(void) { return 801; }
hipError_t hipTexObjectCreate(void) { return 801; }
hipError_t hipTexObjectDestroy(void) { return 801; }
hipError_t hipTexObjectGetResourceDesc(void) { return 801; }
hipError_t hipTexObjectGetResourceViewDesc(void) { return 801; }
hipError_t hipTexObjectGetTextureDesc(void) { return 801; }
hipError_t hipTexRefGetAddress(void) { return 801; }
hipError_t hipTexRefGetAddressMode(void) { return 801; }
hipError_t hipTexRefGetArray(void) { return 801; }
hipError_t hipTexRefGetBorderColor(void) { return 801; }
hipError_t hipTexRefGetFilterMode(void) { return 801; }
hipError_t hipTexRefGetFlags(void) { return 801; }
hipError_t hipTexRefGetFormat(void) { return 801; }
hipError_t hipTexRefGetMaxAnisotropy(void) { return 801; }
hipError_t hipTexRefGetMipMappedArray(void) { return 801; }
hipError_t hipTexRefGetMipmapFilterMode(void) { return 801; }
hipError_t hipTexRefGetMipmapLevelBias(void) { return 801; }
hipError_t hipTexRefGetMipmapLevelClamp(void) { return 801; }
hipError_t hipTexRefSetAddress(void) { return 801; }
hipError_t hipTexRefSetAddress2D(void) { return 801; }
hipError_t hipTexRefSetAddressMode(void) { return 801; }
hipError_t hipTexRefSetArray(void) { return 801; }
hipError_t hipTexRefSetBorderColor(void) { return 801; }
hipError_t hipTexRefSetFilterMode(void) { return 801; }
hipError_t hipTexRefSetFlags(void) { return 801; }
hipError_t hipTexRefSetFormat(void) { return 801; }
hipError_t hipTexRefSetMaxAnisotropy(void) { return 801; }
hipError_t hipTexRefSetMipmapFilterMode(void) { return 801; }
hipError_t hipTexRefSetMipmapLevelBias(void) { return 801; }
hipError_t hipTexRefSetMipmapLevelClamp(void) { return 801; }
hipError_t hipTexRefSetMipmappedArray(void) { return 801; }
hipError_t hipUnbindTexture(void) { return 801; }
hipError_t hipUserObjectCreate(void) { return 801; }
hipError_t hipUserObjectRelease(void) { return 801; }
hipError_t hipUserObjectRetain(void) { return 801; }
hipError_t hipWaitExternalSemaphoresAsync(void) { return 801; }

hipError_t hipCtxCreate(void) { return 801; }
hipError_t hipCtxDestroy(void) { return 801; }
hipError_t hipCtxDisablePeerAccess(void) { return 801; }
hipError_t hipCtxEnablePeerAccess(void) { return 801; }
hipError_t hipCtxGetApiVersion(void) { return 801; }
hipError_t hipCtxGetCacheConfig(void) { return 801; }
hipError_t hipCtxGetDevice(void) { return 801; }
hipError_t hipCtxGetFlags(void) { return 801; }
hipError_t hipCtxGetSharedMemConfig(void) { return 801; }
hipError_t hipCtxPopCurrent(void) { return 801; }
hipError_t hipCtxPushCurrent(void) { return 801; }
hipError_t hipCtxSetCacheConfig(void) { return 801; }
hipError_t hipCtxSetSharedMemConfig(void) { return 801; }
hipError_t hipCtxSynchronize(void) { return 801; }
hipError_t hipDevicePrimaryCtxRelease(void) { return 801; }
hipError_t hipDevicePrimaryCtxReset(void) { return 801; }
hipError_t hipDevicePrimaryCtxSetFlags(void) { return 801; }
